"""Bundle the modular `src/cp` package into the single-cell `notebooks/cp_framework.py` that the
pipeline notebooks `%run`. This is the deploy-time step that lets us author clean per-file modules
(one connector per file, auto-registered) while the Fabric runtime stays the zero-setup %run model.

  python cp_bundle.py            # regenerate notebooks/cp_framework.py from src/cp
  python cp_bundle.py --check    # build + validate, but do not write

Order matters only for module-level executable statements (constants + registry decorators run at
cell load); function bodies resolve names lazily in the flat namespace. Intra-package imports
(`from .x import y`) are stripped — everything shares one namespace in the cell — and the folder
globs give the same "drop a file, it's included" property the real package gets from pkgutil.
"""
import ast
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "src" / "cp"
OUT = HERE.parent / "notebooks" / "cp_framework.py"

# Explicit dependency order for the modules that have module-level executable code / registries.
# Folder contents (connectors/*, discovery/*, cleanse/*, workers/*) are globbed so new files are
# picked up automatically.
LEAD = ["runtime.py", "naming.py", "dag.py", "storage.py", "secrets.py", "config_db.py",
        "transform.py", "audit.py"]

_STRIP_IMPORT = re.compile(r"^\s*(from\s+\.+[\w.]*\s+import|from\s+cp[\s.]|import\s+cp[\s.])")


def _clean(text):
    """Drop intra-package imports and sentinel-marked (bundler:strip) blocks; keep everything else."""
    out, skipping = [], False
    for ln in text.splitlines():
        if "--8<-- strip" in ln:
            skipping = True
            continue
        if "--8<-- endstrip" in ln:
            skipping = False
            continue
        if skipping:
            continue
        if _STRIP_IMPORT.match(ln):
            continue
        out.append(ln)
    return "\n".join(out).strip("\n")


def _folder(name, *, skip=()):  # sorted *.py in a subpackage, excluding __init__ and `skip`
    return sorted(p for p in (SRC / name).glob("*.py")
                  if p.name != "__init__.py" and p.name not in skip)


def _modules():
    mods = [SRC / m for m in LEAD]
    mods += [SRC / "cleanse" / "__init__.py"] + _folder("cleanse")
    mods += [SRC / "connectors" / "__init__.py", SRC / "connectors" / "base.py"]
    mods += _folder("connectors", skip=("base.py",))
    mods += [SRC / "discovery" / "__init__.py"] + _folder("discovery")
    mods += [SRC / "gold.py"]
    mods += [SRC / "workers" / m for m in ("plan.py", "bronze.py", "silver.py", "metadata.py",
                                           "gold.py", "dropbox.py")]
    return mods


HEADER = ('"""cp_framework — GENERATED by deploy/cp_bundle.py from src/cp/. DO NOT EDIT HERE.\n'
          'Edit the modules under control_plane/src/cp/ and re-run cp_bundle.py.\n'
          'Deployed as a single-cell Fabric notebook; engine notebooks `%run cp_framework`.\n"""\n')

FOOTER = ('\n\n# --- worker namespace (so the thin notebooks call workers.<layer>(...) identically\n'
          '#     whether this is the %run bundle or, later, `from cp import workers`) ---\n'
          'import types as _types\n'
          'workers = _types.SimpleNamespace(plan=plan, bronze=bronze, silver=silver,\n'
          '                                 metadata=metadata, gold=gold, dropbox=dropbox)\n\n'
          'print("cp_framework loaded")\n')

# The public API the workers / notebooks / deploy rely on — every name must survive bundling.
EXPECTED_PUBLIC = {
    "var", "tpath", "now_ts", "snake", "_norm_ident", "landed_table", "topo_levels",
    "delta_exists", "read_path", "write_path", "read_config", "files_put", "get_secret",
    "config_conn", "config_query", "config_exec", "config_exec_many",
    "business_cols", "row_hash", "merge_upsert",
    "append_rows", "seed_control_tables", "start_run", "finish_run", "log_object_run",
    "get_watermark", "update_watermark",
    "apply_cleansing", "register_cleanse_function",
    "resolve_connector", "run_connector", "register_ingest_connector", "apply_select",
    "_resolve_conn", "_opts", "_conn", "jdbc_read", "_jdbc_driver", "_jdbc_load",
    "discover_objects", "register_discoverer",
    "gold_write", "build_stage_and_gold",
    "plan", "bronze", "silver", "metadata", "gold", "dropbox", "workers",
}
EXPECTED_REGISTRY_DECOS = {  # name in a decorator/register call -> proves the file is bundled
    "sqlserver", "postgresql", "mysql", "jdbc", "oracle", "db2", "odbc", "http", "rest_api",
    "api", "statcan_wds", "onprem", "staged",   # ingest connectors
    "trim", "normalize_text", "fill_nulls", "parse_datetime", "mask",  # cleanse
}


def build():
    body = HEADER + "\n\n".join(_clean(m.read_text(encoding="utf-8")) for m in _modules())
    return body.rstrip("\n") + FOOTER


def validate(src):
    tree = ast.parse(src)  # raises SyntaxError if the bundle is malformed
    top = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            top.add(node.name)
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    top.add(t.id)
    missing = EXPECTED_PUBLIC - top
    if missing:
        raise SystemExit(f"BUNDLE MISSING public symbols: {sorted(missing)}")
    for name in EXPECTED_REGISTRY_DECOS:
        if f'"{name}"' not in src and f"'{name}'" not in src:
            raise SystemExit(f"BUNDLE MISSING registry entry: {name}")
    return len(src.splitlines()), len(top)


def main():
    src = build()
    lines, syms = validate(src)
    print(f"bundle OK: {lines} lines, {syms} top-level symbols, all public API + registries present")
    if "--check" in sys.argv:
        return
    OUT.write_text(src + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
