"""Export authored config from the config SQL Database back to YAML.

Tables are the source of truth (users edit them via T-SQL in Fabric); YAML is the
promotion artifact. Primary sync direction: SQL -> YAML. Run before promoting,
commit the YAML, then cp_config applies it to the target env.
    python cp_export_config.py
"""
import yaml

import cp_common as C
import cp_sqldb as S

HEADER = ("# GENERATED by cp_export_config from the config SQL Database.\n"
          "# Tables are the source of truth (edit them in Fabric); this YAML is a\n"
          "# promotion artifact consumed by cp_config. Do NOT hand-edit.\n")


def _clean(cols, row):
    rec = {}
    for c, v in zip(cols, row):
        if v is None:
            continue
        if c in S.BOOL_COLS:
            v = bool(v)
        elif isinstance(v, float) and v.is_integer():
            v = int(v)
        rec[c] = v
    return rec


def _fetch(cur, table):
    collist = ",".join(f"[{c}]" for c in S.COLUMNS[table])   # bracket-quote (reserved words)
    cur.execute(f"SELECT {collist} FROM dbo.{table} ORDER BY {S.ORDER_BY[table]}")
    cols = [d[0] for d in cur.description]
    return [_clean(cols, row) for row in cur.fetchall()]


def _dump(path, data):
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False, allow_unicode=True)
    n = len(data) if isinstance(data, list) else sum(len(v) for v in data.values())
    print(f"  wrote {path.name} ({n} rows)")


def main():
    cn = S.connect()
    cur = cn.cursor()
    print(f"Exporting config from SQL Database '{S.CONFIG_DB_NAME}' ({C.WS_NAME}) -> YAML:")
    _dump(C.CONFIG_DIR / "datasource.yml", _fetch(cur, "datasource"))
    _dump(C.CONFIG_DIR / "source_object.yml", _fetch(cur, "source_object"))
    _dump(C.CONFIG_DIR / "dq_rule.yml", _fetch(cur, "dq_rule"))
    _dump(C.CONFIG_DIR / "cleanse_rule.yml", _fetch(cur, "cleanse_rule"))
    _dump(C.CONFIG_DIR / "gold_model.yml", {
        "model": _fetch(cur, "model"),
        "gold_object": _fetch(cur, "gold_object"),
        "gold_dependency": _fetch(cur, "gold_dependency"),
    })
    _dump(C.CONFIG_DIR / "steps.yml", _fetch(cur, "steps"))
    _dump(C.CONFIG_DIR / "pbi_dataset.yml", _fetch(cur, "pbi_dataset"))
    _dump(C.CONFIG_DIR / "security_policy.yml", _fetch(cur, "security_policy"))
    cn.close()


if __name__ == "__main__":
    main()
