"""Export authored config from the lakehouse control tables back to YAML.

Tables are the source of truth (users edit them directly in Fabric); YAML is the
promotion artifact. This is the primary sync direction: table -> YAML. Run before
promoting, then commit the YAML and let cp_config apply it to the target env.

    python cp_export_config.py           # export DEV (CP_TARGET_WORKSPACE overrides)
"""
import math

import pandas as pd
import yaml

import cp_common as C

DROP = {"created_at", "updated_at"}  # bookkeeping cols cp_config re-adds on load


def _scalar(v):
    if hasattr(v, "item"):          # numpy -> python native
        v = v.item()
    if isinstance(v, float) and v.is_integer():
        v = int(v)                  # 0.0 -> 0 for clean YAML
    return v


def _clean(df):
    """DataFrame -> list of dicts, dropping bookkeeping cols and null fields."""
    out = []
    for _, row in df.iterrows():
        rec = {}
        for k, v in row.items():
            if k in DROP:
                continue
            if v is None or (isinstance(v, float) and math.isnan(v)):
                continue
            rec[k] = _scalar(v)
        out.append(rec)
    return out


HEADER = ("# GENERATED by cp_export_config from the lakehouse control tables.\n"
          "# Tables are the source of truth (edit them in Fabric); this YAML is a\n"
          "# promotion artifact consumed by cp_config. Do NOT hand-edit.\n")


def _dump(path, data):
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False, allow_unicode=True)
    print(f"  wrote {path.name} ({len(data) if isinstance(data, list) else sum(len(v) for v in data.values())} rows)")


def main():
    tok = C.storage_token()
    cfg = C.LH["config"]

    def tbl(name):
        return _clean(C.read_delta(cfg, name, tok))

    print(f"Exporting config from '{C.WS_NAME}' -> YAML:")
    _dump(C.CONFIG_DIR / "datasource.yml", tbl("datasource"))
    _dump(C.CONFIG_DIR / "source_object.yml", tbl("source_object"))
    _dump(C.CONFIG_DIR / "dq_rule.yml", tbl("dq_rule"))
    _dump(C.CONFIG_DIR / "gold_model.yml", {
        "model": tbl("model"),
        "gold_object": tbl("gold_object"),
        "gold_dependency": tbl("gold_dependency"),
    })


if __name__ == "__main__":
    main()
