"""cp_framework — GENERATED by deploy/cp_bundle.py from src/cp/. DO NOT EDIT HERE.
Edit the modules under control_plane/src/cp/ and re-run cp_bundle.py.
Deployed as a single-cell Fabric notebook; engine notebooks `%run cp_framework`.
"""
"""Runtime self-configuration: the Spark session, notebookutils, the cp_vars Variable Library,
resolved lakehouse GUIDs, workspace id, and the config SQL DB id. Imported by every other
module. NO hardcoded IDs — everything resolves from the running Fabric context.

In a notebook (%run bundle or wheel) `spark`/`notebookutils` come from the live session; off
cluster these imports fail, which is expected — only the pure modules (naming, dag) import
cleanly off cluster.
"""
import notebookutils
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

try:
    _VL = notebookutils.variableLibrary.getLibrary("cp_vars")
except Exception:
    _VL = None


def var(name, default=None):
    return getattr(_VL, name, default) if _VL is not None else default


LAYER_NAMES = {
    "config": var("config_lakehouse", "LH_metadata"),
    "bronze": var("bronze_lakehouse", "LH_bronze"),
    "silver": var("silver_lakehouse", "LH_silver"),
    "gold":   var("gold_lakehouse", "LH_gold"),
}
SOURCE_SERVER = var("source_server", None)
SOURCE_CONNECTION = var("source_connection", "")
KEY_VAULT_URL = var("key_vault_url", None)

WS_ID = notebookutils.runtime.context["currentWorkspaceId"]
_lh_by_name = {l["displayName"]: l["id"] for l in notebookutils.lakehouse.list()}
LH = {logical: _lh_by_name[name] for logical, name in LAYER_NAMES.items()}
STAGE_LH, QUAR_LH = LH["gold"], LH["silver"]  # stage_/quarantine_ prefixed tables

# Authored config lives in a Fabric SQL Database (users edit it via T-SQL). The engine
# reads it from the SQL DB's OneLake mirror (Delta). Runtime state stays in the lakehouse.
CONFIG_DB_NAME = "config_db"

CONTROL_COLS = {
    "_run_id", "_source_system", "_source_table", "_bronze_ingest_ts",
    "_silver_run_id", "_silver_updated_at", "_row_hash", "_is_current",
    "_effective_start_ts", "_effective_end_ts", "_gold_run_id", "_gold_updated_at",
    "_ingested_at",
}


def _fabric_api_token():
    import requests  # noqa: F401
    for aud in ("pbi", "https://api.fabric.microsoft.com", "https://analysis.windows.net/powerbi/api"):
        try:
            return notebookutils.credentials.getToken(aud)
        except Exception:
            continue
    return None


def _resolve_config_sqldb():
    import requests
    tk = _fabric_api_token()
    r = requests.get(f"https://api.fabric.microsoft.com/v1/workspaces/{WS_ID}/items?type=SQLDatabase",
                     headers={"Authorization": f"Bearer {tk}"})
    for i in r.json().get("value", []):
        if i["displayName"] == CONFIG_DB_NAME:
            return i["id"]
    raise Exception(f"{CONFIG_DB_NAME} SQL Database not found in workspace {WS_ID}")


CONFIG_SQLDB_ID = _resolve_config_sqldb()


def tpath(lh_key_or_guid, table, schema="dbo"):
    # Schema-enabled lakehouses store tables at Tables/<schema>/<table>. Control/audit tables
    # default to the `dbo` schema; bronze/silver land under their datasource schema.
    guid = LH.get(lh_key_or_guid, lh_key_or_guid)
    return f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{guid}/Tables/{schema}/{table}"

"""Pure naming/identifier helpers — no Fabric/Spark dependency, unit-testable off-cluster."""
import json
import re
from datetime import datetime, timezone


def now_ts():
    return datetime.now(timezone.utc).replace(tzinfo=None)


def snake(name):
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", str(name))
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()


def _norm_ident(s):
    """Lowercase, non-alphanumeric -> _, collapse/strip underscores."""
    return re.sub(r"_+", "_", re.sub(r"[^0-9A-Za-z]+", "_", str(s or "").strip().lower())).strip("_")


def landed_table(o):
    """The landed (schema, table) for a source object on a SCHEMA-ENABLED lakehouse:
        schema = datasource (source_name)
        table  = {source_schema|dbo}_{source_table}[_{suffix}]
    e.g. source 'Stats Can', schema null, table 'labour_force', suffix 'bc'
         -> ('stats_can', 'dbo_labour_force_bc')  ->  stats_can.dbo_labour_force_bc."""
    schema = _norm_ident(o.get("source_name")) or "dbo"
    # explicit override (source_options_json.landed = {schema?, table}) — used by the dropbox
    # intake so files land as clean <schema>.<file[_tab]> with no synthetic "dbo_" prefix.
    if o.get("source_options_json"):
        try:
            lt = (json.loads(o["source_options_json"]) or {}).get("landed")
        except (ValueError, TypeError):
            lt = None
        if lt and lt.get("table"):
            return _norm_ident(lt.get("schema")) or schema, _norm_ident(lt["table"])
    parts = [(o.get("source_schema") or "dbo"), o.get("source_table")]
    name = "_".join(_norm_ident(p) for p in parts if p)
    if o.get("suffix"):
        name = f"{name}_{_norm_ident(o['suffix'])}"
    return schema, name

"""Pure DAG helper — topological levelization for the gold build order. No dependencies."""


def topo_levels(nodes, edges):
    remaining, done = set(nodes), set()
    parents = {n: set() for n in nodes}
    for p, c in edges:
        if c in parents and p in remaining:
            parents[c].add(p)
    levels = []
    while remaining:
        ready = sorted([n for n in remaining if parents[n] <= done])
        if not ready:
            raise ValueError(f"cycle in gold DAG: {remaining}")
        levels.append(ready)
        done |= set(ready)
        remaining -= set(ready)
    return levels

"""OneLake Delta I/O + the config-DB OneLake mirror reader + Files writes."""
from pyspark.sql import functions as F
from delta.tables import DeltaTable



def delta_exists(path):
    try:
        return DeltaTable.isDeltaTable(spark, path)
    except Exception:
        return False


def read_path(path):
    return spark.read.format("delta").load(path)


def write_path(df, path, mode="overwrite"):
    w = df.write.format("delta").mode(mode)
    w = w.option("overwriteSchema", "true") if mode == "overwrite" else w.option("mergeSchema", "true")
    w.save(path)


def read_config(table):
    """Read an authored-config table from the config SQL DB's OneLake mirror.
    BIT columns mirror as boolean; normalize is_active so filters are robust."""
    df = read_path(f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/"
                   f"{CONFIG_SQLDB_ID}/Tables/dbo/{table}")
    if "is_active" in df.columns:
        df = df.withColumn("is_active", F.col("is_active").cast("boolean"))
    return df


def files_put(name, text):
    """Write a text file to the config lakehouse Files area (GUID path)."""
    p = f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{LH['config']}/Files/{name}"
    notebookutils.fs.put(p, text, True)

"""Key Vault secret access (uses the running identity's token)."""


def get_secret(name):
    """Read a secret from the Key Vault named by the cp_vars `key_vault_url` variable
    (uses the running identity's token — grant it KV 'get' on that vault)."""
    if not name:
        return None
    if not KEY_VAULT_URL:
        raise Exception("cp_vars.key_vault_url is not set — cannot resolve secret " + str(name))
    return notebookutils.credentials.getSecret(KEY_VAULT_URL, name)

"""Direct config-DB access (pyodbc + AAD token) — used by the planner and workers to read
authored config and (for discovery) register source_object rows."""


def _config_props():
    import requests
    tk = _fabric_api_token()
    h = {"Authorization": f"Bearer {tk}"}
    for d in requests.get(f"https://api.fabric.microsoft.com/v1/workspaces/{WS_ID}/SqlDatabases",
                          headers=h).json().get("value", []):
        if d["displayName"] == CONFIG_DB_NAME:
            p = requests.get(f"https://api.fabric.microsoft.com/v1/workspaces/{WS_ID}/"
                             f"SqlDatabases/{d['id']}", headers=h).json()["properties"]
            return p["serverFqdn"].split(",")[0], p["databaseName"]
    raise Exception(f"{CONFIG_DB_NAME} not found")


def config_conn(retries=4):
    import pyodbc
    import struct
    import time
    host, database = _config_props()
    tok = notebookutils.credentials.getToken("https://database.windows.net/").encode("utf-16-le")
    ts = struct.pack(f"<I{len(tok)}s", len(tok), tok)
    cs = (f"DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={host};DATABASE={database};"
          "Encrypt=yes;Connection Timeout=60")
    last = None
    for a in range(retries):
        try:
            return pyodbc.connect(cs, attrs_before={1256: ts}, timeout=60)
        except pyodbc.Error as e:                        # serverless SQL endpoint cold-start / throttle
            last = e
            if any(s in str(e) for s in ("HYT00", "08001", "timeout", "Timeout")):
                time.sleep(10 * (a + 1))
                continue
            raise
    raise last


def config_query(sql, params=()):
    cn = config_conn()
    cur = cn.cursor()
    cur.execute(sql, *params)
    cols = [d[0] for d in cur.description]
    rows = [dict(zip(cols, r)) for r in cur.fetchall()]
    cn.close()
    return rows


def config_exec(sql, params=()):
    """Execute a write against config_db (used by object discovery to register source_object)."""
    cn = config_conn()
    cur = cn.cursor()
    cur.execute(sql, *params)
    cn.commit()
    cn.close()


def config_exec_many(sql, rows):
    """Batch-insert into config_db on a single connection (one connect per datasource, not per row)."""
    if not rows:
        return
    cn = config_conn()
    cur = cn.cursor()
    cur.fast_executemany = True
    cur.executemany(sql, rows)
    cn.commit()
    cn.close()

"""Row-level transform helpers: business-column selection, row hashing, and Delta upsert."""
from pyspark.sql import functions as F
from delta.tables import DeltaTable



def business_cols(df):
    return [c for c in df.columns if c not in CONTROL_COLS and not c.startswith("_")]


def row_hash(df, cols=None, out="_row_hash"):
    cols = cols or business_cols(df)
    if not cols:
        return df.withColumn(out, F.sha2(F.lit(""), 256))
    exprs = [F.coalesce(F.col(c).cast("string"), F.lit("<NULL>")) for c in cols]
    return df.withColumn(out, F.sha2(F.concat_ws("||", *exprs), 256))


def merge_upsert(target_path, source_df, keys):
    if not delta_exists(target_path):
        write_path(source_df, target_path, mode="overwrite")
        return
    tgt = DeltaTable.forPath(spark, target_path)
    cond = " AND ".join([f"t.`{k}` = s.`{k}`" for k in keys])
    (tgt.alias("t").merge(source_df.alias("s"), cond)
        .whenMatchedUpdateAll().whenNotMatchedInsertAll().execute())

"""Control/audit tables: run + per-object logging, watermarks, and their explicit schemas.
Appends are idempotent-ish (append-only markers); seed_control_tables pre-creates the empty
tables so parallel ForEach workers don't race to CREATE them on a fresh lakehouse."""
import json

from pyspark.sql import functions as F


# Explicit schemas so all-None columns (e.g. run_completed_at) don't break inference.
SCHEMAS = {
    "ingestion_run": "run_id string, run_started_at timestamp, run_completed_at timestamp, status string, details string",
    "object_load_run": ("run_id string, object_id string, layer string, status string, "
                        "source_count long, target_count long, quarantine_count long, "
                        "started_at timestamp, ended_at timestamp, details string"),
    "watermark_state": "object_id string, watermark_value string, updated_at timestamp",
    "schema_drift_event": ("event_id string, run_id string, object_id string, column_name string, "
                          "drift_type string, severity string, details string, detected_at timestamp"),
    "dq_result": ("run_id string, object_id string, rule_id string, failed_count long, "
                  "passed_count long, status string, evaluated_at timestamp"),
    "parity_result": ("run_id string, object_id string, check_scope string, check_name string, "
                      "source_value string, target_value string, status string, checked_at timestamp"),
    "pipeline_run_log": ("pipeline_name string, run_id string, load_group int, activity string, "
                         "message string, logged_at timestamp"),
    "dropbox_ledger": ("file_key string, content_hash string, schema_name string, "
                       "object_count int, status string, processed_at timestamp"),
}


def _json_safe(d):
    return {k: (json.dumps(v) if isinstance(v, (dict, list)) else v) for k, v in d.items()}


def _to_int(v):
    return int(v) if v is not None else None


def append_rows(config_table, rows):
    if not rows:
        return
    rows = [_json_safe(r) for r in rows]
    schema = SCHEMAS.get(config_table)
    if schema:
        # order dict values to the schema's column order
        cols = [c.strip().split()[0] for c in schema.split(",")]
        rows = [[r.get(c) for c in cols] for r in rows]
        df = spark.createDataFrame(rows, schema)
    else:
        df = spark.createDataFrame(rows)
    write_path(df, tpath("config", config_table), mode="append")


def seed_control_tables():
    """Pre-create the append-target control tables (empty) so concurrent ForEach workers don't
    race to CREATE them on a fresh lakehouse (Delta 'multiple writers to an empty directory')."""
    for name, schema in SCHEMAS.items():
        p = tpath("config", name)
        if not delta_exists(p):
            write_path(spark.createDataFrame([], schema), p, mode="overwrite")


def start_run(run_id, details=None):
    append_rows("ingestion_run", [{
        "run_id": run_id, "run_started_at": now_ts(), "run_completed_at": None,
        "status": "RUNNING", "details": json.dumps(details or {})}])
    return run_id


def finish_run(run_id, status="SUCCEEDED", details=None):
    # append-only completion marker (avoids UPDATE for simplicity/idempotence)
    append_rows("ingestion_run", [{
        "run_id": run_id, "run_started_at": now_ts(), "run_completed_at": now_ts(),
        "status": status, "details": json.dumps(details or {})}])


def log_object_run(run_id, object_id, layer, status, source_count=None,
                   target_count=None, quarantine_count=None, details=None):
    append_rows("object_load_run", [{
        "run_id": run_id, "object_id": object_id, "layer": layer, "status": status,
        "source_count": _to_int(source_count), "target_count": _to_int(target_count),
        "quarantine_count": _to_int(quarantine_count), "started_at": now_ts(),
        "ended_at": now_ts(), "details": json.dumps(details or {})}])


def get_watermark(object_id):
    p = tpath("config", "watermark_state")
    if not delta_exists(p):
        return None
    rows = (read_path(p).where(F.col("object_id") == object_id)
            .orderBy(F.col("updated_at").desc()).limit(1).collect())
    return rows[0]["watermark_value"] if rows else None


def update_watermark(object_id, value):
    if value is None:
        return
    append_rows("watermark_state", [{
        "object_id": object_id, "watermark_value": str(value), "updated_at": now_ts()}])

"""Cleansing registry. Add a cleanse function by dropping a module in this folder and
decorating it with @cleanse_fn("name") — no edits here. Applied on silver, config-driven."""
import json

CLEANSE_FUNCS = {}


def cleanse_fn(*names):
    """Register a cleanse function under one or more names. Signature: (df, cols:list, params:dict) -> df."""
    def deco(fn):
        for n in names:
            CLEANSE_FUNCS[n] = fn
        return fn
    return deco


def register_cleanse_function(name, fn):
    """Imperative registration (equivalent to @cleanse_fn)."""
    CLEANSE_FUNCS[name] = fn


def apply_cleansing(df, rules):
    """Apply active cleanse rules (list of dicts) in apply_order. Ignores unknown functions."""
    for r in sorted(rules, key=lambda x: (x.get("apply_order") or 0)):
        fn = CLEANSE_FUNCS.get(r.get("function"))
        if not fn:
            continue
        cols = [c.strip() for c in str(r.get("columns") or "").split(";") if c.strip()]
        params = json.loads(r["parameters_json"]) if r.get("parameters_json") else {}
        df = fn(df, cols, params)
    return df

"""Built-in cleanse functions. Each registers itself via @cleanse_fn — extend by adding a
sibling module with more @cleanse_fn functions; nothing here needs editing."""
from pyspark.sql import functions as F



@cleanse_fn("trim")
def _cf_trim(df, cols, p):
    for c in cols:
        if c in df.columns:
            df = df.withColumn(c, F.trim(F.col(c).cast("string")))
    return df


@cleanse_fn("normalize_text")
def _cf_normalize_text(df, cols, p):
    case = p.get("case")
    for c in cols:
        if c not in df.columns:
            continue
        col = F.trim(F.col(c).cast("string"))
        if p.get("collapse_spaces", True):
            col = F.regexp_replace(col, r"\s+", " ")
        if case == "lower":
            col = F.lower(col)
        elif case == "upper":
            col = F.upper(col)
        elif case == "title":
            col = F.initcap(col)
        if p.get("empty_as_null", True):
            col = F.when(col == "", None).otherwise(col)
        df = df.withColumn(c, col)
    return df


@cleanse_fn("fill_nulls")
def _cf_fill_nulls(df, cols, p):
    default = p.get("default", p.get("value"))
    for c in cols:
        if c in df.columns:
            df = df.withColumn(c, F.coalesce(F.col(c), F.lit(default)))
    return df


@cleanse_fn("parse_datetime")
def _cf_parse_datetime(df, cols, p):
    conv = F.to_date if p.get("target_type", "date") == "date" else F.to_timestamp
    formats = p.get("formats", ["yyyy-MM-dd"])
    for c in cols:
        if c not in df.columns:
            continue
        parsed = F.lit(None)
        for fmt in formats:
            parsed = F.coalesce(parsed, conv(F.col(c).cast("string"), fmt))
        df = df.withColumn(p.get("into") or c, parsed)
    return df


def _cf_case(fn):
    def apply(df, cols, p):
        for c in cols:
            if c in df.columns:
                df = df.withColumn(c, fn(F.col(c).cast("string")))
        return df
    return apply


@cleanse_fn("replace")
def _cf_replace(df, cols, p):
    for c in cols:
        if c in df.columns:
            df = df.withColumn(c, F.regexp_replace(F.col(c).cast("string"),
                                                   p.get("pattern", ""), p.get("replacement", "")))
    return df


@cleanse_fn("mask")
def _cf_mask(df, cols, p):
    """Static masking (stored masked — enforced on EVERY engine). style: redact|hash|partial."""
    style = p.get("style", "redact")
    for c in cols:
        if c not in df.columns:
            continue
        col = F.col(c).cast("string")
        if style == "hash":
            df = df.withColumn(c, F.sha2(col, 256))
        elif style == "partial":                        # keep last N chars, e.g. ***1234
            keep = int(p.get("keep", 4))
            df = df.withColumn(c, F.concat(F.lit(p.get("prefix", "***")),
                                           F.substring(col, -keep, keep)))
        else:                                            # redact
            df = df.withColumn(c, F.lit(p.get("replacement", "***")))
    return df


register_cleanse_function("to_upper", _cf_case(F.upper))
register_cleanse_function("to_lower", _cf_case(F.lower))
register_cleanse_function("to_title", _cf_case(F.initcap))

"""Ingestion connector registry. Add a source by dropping a module in this folder and
decorating its function with @ingest_connector("name", ...) — you never edit this file or the
framework. A connector is fn(object_config: dict, user, password) -> raw Spark DataFrame.
object_config carries source_object + datasource fields (see workers.plan), plus the parsed
JSON columns connection_json (datasource-level) and source_options_json (per object)."""

INGEST_CONNECTORS = {}
# connectors that support metadata schema discovery (INFORMATION_SCHEMA over JDBC)
DISCOVERABLE_CONNECTORS = {"sqlserver", "oracle", "db2", "postgresql", "mysql", "jdbc"}


def ingest_connector(*names):
    """Register a connector under one or more names/aliases."""
    def deco(fn):
        for n in names:
            INGEST_CONNECTORS[n] = fn
        return fn
    return deco


def register_ingest_connector(name, fn):
    """Imperative registration (equivalent to @ingest_connector)."""
    INGEST_CONNECTORS[name] = fn


def resolve_connector(o):
    """The connector key for a source object: explicit `connector`, else `source_type`."""
    name = (o.get("connector") or o.get("source_type") or "sqlserver").lower()
    return {"sql": "sqlserver", "mssql": "sqlserver", "custom_jdbc": "sqlserver",
            "api": "rest_api", "statcan": "statcan_wds"}.get(name, name)


def run_connector(o, user, password):
    """Dispatch to the datasource's connector and return the raw extract DataFrame."""
    name = resolve_connector(o)
    fn = INGEST_CONNECTORS.get(name)
    if not fn:
        raise Exception(f"no ingest connector registered for '{name}' (object {o.get('object_id')})")
    return fn(o, user, password)

"""Shared connector helpers: connection resolution (KV + connection_json), JDBC dialects/loader,
driver-side DB-API bridge, on-demand pip, JSON pointer, and config-driven column selection."""
import json
import re

from pyspark.sql import functions as F


COMPLEX_TYPES = {"xml", "geography", "geometry", "hierarchyid", "varbinary", "image", "sql_variant"}

# jdbc dialects: driver class + url template + default port. The SQL Server driver ships with
# Fabric Spark; Oracle/DB2/Postgres/MySQL need their JDBC jar added to the Fabric Environment.
JDBC_DIALECTS = {
    "sqlserver":  {"driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver", "port": 1433,
                   "url": "jdbc:sqlserver://{host}:{port};database={database};encrypt=true;trustServerCertificate=true;loginTimeout=60"},
    "oracle":     {"driver": "oracle.jdbc.OracleDriver", "port": 1521,
                   "url": "jdbc:oracle:thin:@//{host}:{port}/{database}"},
    "db2":        {"driver": "com.ibm.db2.jcc.DB2Driver", "port": 50000,
                   "url": "jdbc:db2://{host}:{port}/{database}"},
    "postgresql": {"driver": "org.postgresql.Driver", "port": 5432,
                   "url": "jdbc:postgresql://{host}:{port}/{database}"},
    "mysql":      {"driver": "com.mysql.cj.jdbc.Driver", "port": 3306,
                   "url": "jdbc:mysql://{host}:{port}/{database}"},
}


def _jdbc_driver(c, d):
    """Resolve the JDBC driver class. Accepts a real class, a dialect name (e.g. 'sqlserver' in a
    secret), or falls back to the dialect preset."""
    drv = c.get("driver")
    if drv in JDBC_DIALECTS:
        return JDBC_DIALECTS[drv]["driver"]
    return drv or (d["driver"] if d else None)


def _jdbc_load(url, driver, user, password, dbtable=None, query=None, tries=4):
    import time
    r = (spark.read.format("jdbc").option("url", url)
         .option("user", user).option("password", password).option("driver", driver))
    r = r.option("query", query) if query else r.option("dbtable", dbtable)
    last = None
    for a in range(tries):
        try:
            return r.load()
        except Exception as e:  # transient connect/timeout -> back off and retry
            last = e
            if any(s in str(e).lower() for s in ("connect", "timed out", "tcp/ip", "reset")):
                time.sleep(15 * (a + 1))
                continue
            raise
    raise last


def jdbc_read(server, database, user, password, dbtable=None, query=None, tries=4):
    """SQL Server JDBC read (back-compat helper used by metadata schema discovery)."""
    d = JDBC_DIALECTS["sqlserver"]
    url = d["url"].format(host=server, port=d["port"], database=database)
    return _jdbc_load(url, d["driver"], user, password, dbtable, query, tries)


def _opts(o):
    return json.loads(o["source_options_json"]) if o.get("source_options_json") else {}


def _conn(o):
    return json.loads(o["connection_json"]) if o.get("connection_json") else {}


def _resolve_conn(o):
    """Full connection params for a source: the KV secret named by datasource.secret_name is the
    base (the COMPLETE connection info — host/port/db/user/password or a raw connection string/url),
    with connection_json layered on top for non-secret overrides (e.g. mode, driver). The secret
    value may be a JSON object (parsed) or a raw string (kept under 'connection_string')."""
    conn = {}
    raw = get_secret(o.get("secret_name")) if o.get("secret_name") else None
    if raw:
        try:
            parsed = json.loads(raw)
            conn = parsed if isinstance(parsed, dict) else {"connection_string": raw}
        except (ValueError, TypeError):
            conn = {"connection_string": raw}
    if o.get("connection_json"):
        conn = {**conn, **json.loads(o["connection_json"])}
    return conn


def _dig(obj, path):
    """Follow a dot-path (e.g. 'a.b.0') into nested JSON/lists."""
    for k in [x for x in str(path or "").split(".") if x]:
        obj = obj[int(k)] if isinstance(obj, list) else obj[k]
    return obj


def _ensure_pkg(import_name, pip_name=None):
    """Import a package, pip-installing it into the session on first use (plug-and-play).
    Used by the pure-Python DB connectors so no Fabric Environment/driver jar is needed."""
    import importlib
    try:
        return importlib.import_module(import_name)
    except ImportError:
        import subprocess
        import sys
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", pip_name or import_name],
                       check=True)
        return importlib.import_module(import_name)


def _default_query(o):
    schema, table = o.get("source_schema"), o.get("source_table")
    return f"SELECT * FROM {schema + '.' if schema else ''}{table}"


def _dbapi_to_spark(cn, query):
    """Run a query over a DB-API connection (driver-side) -> Spark DataFrame."""
    import pandas as pd
    try:
        cur = cn.cursor()
        cur.execute(query)
        cols = [d[0] for d in cur.description]
        rows = [tuple(r) for r in cur.fetchall()]
    finally:
        cn.close()
    if not rows:
        return spark.createDataFrame([], ", ".join(f"`{c}` string" for c in cols))
    pdf = pd.DataFrame(rows, columns=cols)
    pdf = pdf.where(pd.notnull(pdf), None)
    return spark.createDataFrame(pdf)


def apply_select(df, spec):
    """Config-driven schema selection for the landed data (source_options_json.select).
    Controls exactly which columns land, their order, names and types. Forms:
      - ["colA","colB"]                              projection (keep, in order)
      - [{"source":"C","name":"c","type":"double"}]  project + rename + cast
      - {"columns":[...],"rename":{s:n},"cast":{c:t}} projection + rename + cast
    `source` names are the connector's raw output column names. No spec -> land full schema."""
    if not spec:
        return df
    if isinstance(spec, dict):
        sel = spec.get("columns") or df.columns
        out = df.select(*[F.col(c) for c in sel if c in df.columns])
        for src, new in (spec.get("rename") or {}).items():
            if src in out.columns:
                out = out.withColumnRenamed(src, new)
        for c, t in (spec.get("cast") or {}).items():
            if c in out.columns:
                out = out.withColumn(c, F.col(c).cast(t))
        return out
    exprs = []
    for item in spec:
        if isinstance(item, str):
            if item in df.columns:
                exprs.append(F.col(item))
        else:
            src = item.get("source") or item.get("name")
            if src in df.columns:
                e = F.col(src).cast(item["type"]) if item.get("type") else F.col(src)
                exprs.append(e.alias(item.get("name", src)))
    return df.select(*exprs) if exprs else df

"""IBM DB2 connector — pure-Python `ibm_db` by default; JDBC via mode='jdbc'."""


@ingest_connector("db2")
def _ic_db2(o, user, password):
    """IBM DB2. Default: pure-Python `ibm_db` (pip-installed on demand; the wheel bundles the
    client) reading driver-side. Opt in to distributed Spark JDBC (needs the db2jcc jar on an
    attached Fabric Environment) with connection_json.mode='jdbc'."""
    c, opts = _resolve_conn(o), _opts(o)
    if (c.get("mode") or "").lower() == "jdbc":
        return _ic_jdbc(o, user, password)
    user = c.get("user") or user
    password = c.get("password") or password
    dbi = _ensure_pkg("ibm_db_dbi", "ibm_db")
    cs = (f"DATABASE={c.get('database') or o.get('database_name')};HOSTNAME={c.get('host')};"
          f"PORT={c.get('port', 50000)};PROTOCOL=TCPIP;UID={user};PWD={password};")
    return _dbapi_to_spark(dbi.connect(cs, "", ""), opts.get("query") or _default_query(o))

"""Microsoft Entra ID (Azure AD) connector via Microsoft Graph. Loads directory objects from the
tenant named in the KV secret. Client-credentials auth (app registration with the relevant Graph
*Application* permissions + admin consent); the secret holds {tenant_id, client_id, client_secret}.

source_options_json:
    entity        Graph collection path, e.g. "users", "groups", "servicePrincipals",
                  "applications", "directoryRoles", "roleManagement/directory/roleAssignments"
    select        list of $select fields (or a string)
    filter        $filter expression
    expand        $expand (list or string) — e.g. ["principal","roleDefinition"]
    top           $top page size (optional; Graph paginates via @odata.nextLink regardless)
    api           "v1.0" (default) or "beta"
    subresource   RELATIONAL mode: for each item in `entity`, fetch /entity/{id}/<subresource>
                  (e.g. entity="groups", subresource="members") and tag each row with the parent's
                  fields as <singular>_<field> (e.g. group_id, group_displayName).
    parent_fields fields to read from each parent for tagging (default ["id"])
"""
import json
import re


GRAPH = "https://graph.microsoft.com"


def _graph_token(c):
    import requests
    tid = c.get("tenant_id") or c.get("tenant")
    r = requests.post(f"https://login.microsoftonline.com/{tid}/oauth2/v2.0/token",
                      data={"grant_type": "client_credentials", "client_id": c.get("client_id"),
                            "client_secret": c.get("client_secret"), "scope": f"{GRAPH}/.default"},
                      timeout=30)
    r.raise_for_status()
    return r.json()["access_token"]


def _get_all(url, headers):
    """GET a Graph collection, following @odata.nextLink to the end."""
    import requests
    rows = []
    while url:
        r = requests.get(url, headers=headers, timeout=120)
        r.raise_for_status()
        j = r.json()
        rows += j.get("value", [j] if "id" in j else [])
        url = j.get("@odata.nextLink")
    return rows


def _qs(opts):
    parts = []
    sel = opts.get("select")
    if sel:
        parts.append("$select=" + (",".join(sel) if isinstance(sel, list) else str(sel)))
    if opts.get("filter"):
        parts.append("$filter=" + opts["filter"])
    exp = opts.get("expand")
    if exp:
        parts.append("$expand=" + (",".join(exp) if isinstance(exp, list) else str(exp)))
    if opts.get("top"):
        parts.append("$top=" + str(opts["top"]))
    return "&".join(parts)


def _flatten(rows):
    import pandas as pd
    if not rows:
        return None
    pdf = pd.json_normalize(rows)
    for col in pdf.columns:                                   # nested list/dict -> JSON string
        if pdf[col].apply(lambda v: isinstance(v, (list, dict))).any():
            pdf[col] = pdf[col].apply(lambda v: json.dumps(v) if isinstance(v, (list, dict)) else v)
    pdf.columns = [re.sub(r"[^A-Za-z0-9_]", "_", str(c)).strip("_") for c in pdf.columns]
    return pdf.where(pd.notnull(pdf), None)


@ingest_connector("entra", "msgraph", "graph")
def entra(o, user, password):
    c, opts = _resolve_conn(o), _opts(o)
    base = f"{GRAPH}/{opts.get('api', 'v1.0')}"
    headers = {"Authorization": f"Bearer {_graph_token(c)}", "ConsistencyLevel": "eventual"}
    entity = opts.get("entity") or o.get("source_table")

    if opts.get("subresource"):                              # relational: parent -> sub-collection
        sub = opts["subresource"]
        pfields = opts.get("parent_fields", ["id"])
        singular = re.sub(r"s$", "", entity.split("/")[-1])  # groups -> group
        parents = _get_all(f"{base}/{entity}?$select={','.join(pfields)}&$top=999", headers)
        subqs = _qs({k: opts.get(k) for k in ("select", "filter", "expand", "top")})
        rows = []
        for p in parents:
            for row in _get_all(f"{base}/{entity}/{p['id']}/{sub}?{subqs}", headers):
                tagged = {f"{singular}_{k}": p.get(k) for k in pfields}
                tagged.update(row)
                rows.append(tagged)
    else:
        rows = _get_all(f"{base}/{entity}?{_qs(opts)}", headers)

    pdf = _flatten(rows)
    if pdf is None or pdf.empty:
        return spark.createDataFrame([], "id string")
    return spark.createDataFrame(pdf)

"""Ad-hoc file connector for the dropbox intake. Reads ONE object — a csv/txt file, or ONE sheet
of an xlsx/xls workbook — from a OneLake Files path into a **string-typed** Spark DataFrame so the
silver full-row-hash stays stable across re-drops. source_options_json:
    file_abfss   full abfss path to the file (LH_Filedrop/Files/...)
    format       csv | txt | xlsx | xls
    sheet        sheet name (xlsx/xls only)
    sep          delimiter override (csv/txt); omit to default ',' for csv and sniff for txt
"""
import os
import re
import tempfile



def _local_copy(abfss):
    local = os.path.join(tempfile.gettempdir(),
                         f"cp_drop_{_norm_ident(abfss.rsplit('/', 1)[-1])}_{abs(hash(abfss)) % 10**8}")
    notebookutils.fs.cp(abfss, "file:" + local, True)
    return local


@ingest_connector("file", "dropbox")
def file_source(o, user, password):
    import pandas as pd
    opts = _opts(o)
    fmt = (opts.get("format") or "").lower()
    local = _local_copy(opts["file_abfss"])
    try:
        if fmt in ("xlsx", "xls"):
            engine = "openpyxl" if fmt == "xlsx" else "xlrd"
            _ensure_pkg(engine)
            pdf = pd.read_excel(local, sheet_name=opts["sheet"], dtype=str, engine=engine)
        else:                                                # csv / txt
            sep = opts.get("sep")
            if sep is None and fmt == "txt":                 # sniff the delimiter for txt
                pdf = pd.read_csv(local, dtype=str, sep=None, engine="python")
            else:
                pdf = pd.read_csv(local, dtype=str, sep=sep or ",", low_memory=False)
    finally:
        try:
            os.remove(local)
        except OSError:
            pass

    pdf = pdf.dropna(axis=1, how="all")                      # drop fully-empty columns
    pdf.columns = [re.sub(r"[^A-Za-z0-9_]", "_", str(c)).strip("_") or f"col{i}"
                   for i, c in enumerate(pdf.columns)]
    pdf = pdf.where(pd.notnull(pdf), None)
    if pdf.empty:
        schema = ", ".join(f"`{c}` string" for c in pdf.columns) or "_empty string"
        return spark.createDataFrame([], schema)
    return spark.createDataFrame(pdf)

"""Generalized HTTP/API connector — one connector for every API (like ADF's HTTP linked
service + dataset). Differs per source only by source_options_json. Also serves statcan_wds
(a zip_csv profile)."""
import re



@ingest_connector("http", "rest_api", "api", "statcan_wds")
def _ic_http(o, user, password):
    """Generalized HTTP/API connector. Connection (KV secret / connection_json): base_url,
    headers/auth. Request (source_options_json):
       url | path        endpoint; may template {name} from `params` (e.g. .../{table_id}/{language})
       method            GET (default) / POST / ...
       params            values for URL templating AND query string
       query             extra query params (dict)
       body              JSON request body
       headers           per-request headers (merged over connection headers)
       response          how to turn the response into rows:
           {type:"json", record_path:"a.b"}          JSON -> list of records
           {type:"csv"}                               response body IS a CSV
           {type:"zip_csv", url_field:"object",       response JSON has a URL field pointing to a
                            member:<regex>|null,       ZIP; download it and read the CSV member
                            exclude:"_Meta"}           (StatCan WDS pattern)
       filters           {col:value} equality filters at ingest (ORIGINAL column names)
    """
    import requests
    import io
    import pandas as pd
    c, opts = _resolve_conn(o), _opts(o)
    params = opts.get("params", {})
    url = (opts.get("url") or (c.get("base_url", "") + opts.get("path", ""))).format(**params)
    headers = {**c.get("headers", {}), **opts.get("headers", {})}
    resp = requests.request((opts.get("method") or "GET").upper(), url, headers=headers,
                            params=opts.get("query"), json=opts.get("body"), timeout=120)
    resp.raise_for_status()

    r = opts.get("response") or {"type": "json"}
    rtype = r.get("type", "json")
    if rtype == "csv":
        pdf = pd.read_csv(io.BytesIO(resp.content), dtype=str, low_memory=False)
    elif rtype == "zip_csv":                            # follow a JSON pointer to a zip of CSVs
        import zipfile
        zurl = _dig(resp.json(), r.get("url_field", "object"))
        zf = zipfile.ZipFile(io.BytesIO(requests.get(zurl, timeout=600).content))
        member, excl = r.get("member"), r.get("exclude", "_Meta")
        names = [f for f in zf.namelist() if f.lower().endswith(".csv")
                 and (re.search(member, f) if member else (not excl or excl not in f))]
        pdf = pd.read_csv(zf.open(names[0]), dtype=str, low_memory=False)
    else:                                               # json
        data = _dig(resp.json(), r.get("record_path"))
        pdf = pd.json_normalize([data] if isinstance(data, dict) else data)

    for col, val in (opts.get("filters") or {}).items():
        if col in pdf.columns:
            pdf = pdf[pdf[col].astype(str).str.strip() == str(val)]
    pdf.columns = [re.sub(r"[^A-Za-z0-9_]", "_", str(x)) for x in pdf.columns]
    pdf = pdf.where(pd.notnull(pdf), None)
    return spark.createDataFrame(pdf)

"""JDBC connector for any dialect (SQL Server / Postgres / MySQL bundled; generic jdbc)."""


@ingest_connector("sqlserver", "postgresql", "mysql", "jdbc")
def _ic_jdbc(o, user, password):
    """JDBC connector for any dialect. Server/driver from connection_json (or a dialect
    preset); falls back to the cp_vars source_server for SQL Server (back-compat)."""
    name = (o.get("connector") or o.get("source_type") or "sqlserver").lower()
    if name in ("sql", "mssql", "custom_jdbc"):
        name = "sqlserver"
    d = JDBC_DIALECTS.get(name)
    c, opts = _resolve_conn(o), _opts(o)
    user = c.get("user") or user
    password = c.get("password") or password
    driver = _jdbc_driver(c, d)
    if c.get("url") or c.get("connection_string"):
        url = c.get("url") or c.get("connection_string")
    elif d:
        url = d["url"].format(host=c.get("host") or SOURCE_SERVER,
                              port=c.get("port") or d["port"],
                              database=c.get("database") or o.get("database_name"))
    else:
        raise Exception(f"jdbc connector '{name}': set connection_json.url + .driver")
    if not driver:
        raise Exception(f"jdbc connector '{name}': no driver class")
    schema, table, wm_col = o.get("source_schema"), o.get("source_table"), o.get("watermark_column")
    wm = get_watermark(o["object_id"]) if (o.get("load_type") == "incremental" and wm_col) else None
    if opts.get("query"):
        query = opts["query"]
    elif name == "sqlserver":                          # prune JDBC-unreadable complex-type columns
        cols = _jdbc_load(url, driver, user, password, query=(
            "SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS "
            f"WHERE TABLE_SCHEMA='{schema}' AND TABLE_NAME='{table}'")).collect()
        keep = [r["COLUMN_NAME"] for r in cols if r["DATA_TYPE"].lower() not in COMPLEX_TYPES]
        col_sql = ", ".join(f"[{x}]" for x in keep)
        pred = f" WHERE [{wm_col}] > '{wm}'" if wm else ""
        query = f"SELECT {col_sql} FROM [{schema}].[{table}]{pred}"
    else:
        tbl = f"{schema}.{table}" if schema else table
        pred = f" WHERE {wm_col} > '{wm}'" if wm else ""
        query = f"SELECT * FROM {tbl}{pred}"
    return _jdbc_load(url, driver, user, password, query=query)

"""Generic ODBC connector (driver-side pyodbc)."""


@ingest_connector("odbc")
def _ic_odbc(o, user, password):
    """Generic ODBC via pyodbc on the driver node (not distributed — modest volumes).
    connection_json.odbc = an ODBC connection string ({user}/{password} placeholders
    substituted at runtime). Needs the platform ODBC driver/DSN in the Fabric Environment."""
    import pyodbc
    c, opts = _resolve_conn(o), _opts(o)
    user = c.get("user") or user
    password = c.get("password") or password
    cs = c.get("odbc") or c.get("connection_string")
    if not cs:
        raise Exception("odbc connector needs a connection string (secret or connection_json.odbc)")
    cs = cs.format(user=user, password=password,
                   **{k: v for k, v in c.items() if k not in ("odbc", "user", "password")})
    query = opts.get("query")
    if not query:
        schema, table = o.get("source_schema"), o.get("source_table")
        query = f"SELECT * FROM {schema + '.' if schema else ''}{table}"
    cn = pyodbc.connect(cs)
    cur = cn.cursor()
    cur.execute(query)
    cols = [dd[0] for dd in cur.description]
    rows = [tuple(r) for r in cur.fetchall()]
    cn.close()
    if not rows:
        return spark.createDataFrame([], ", ".join(f"`{x}` string" for x in cols))
    return spark.createDataFrame(rows, cols)

"""Oracle connector — pure-Python `oracledb` thin mode by default; JDBC via mode='jdbc'."""


@ingest_connector("oracle")
def _ic_oracle(o, user, password):
    """Oracle. Default: pure-Python `oracledb` THIN mode (pip-installed on demand, no Oracle
    client, no jar) reading driver-side. Opt in to distributed Spark JDBC (needs the ojdbc jar
    on an attached Fabric Environment) with connection_json.mode='jdbc'."""
    c, opts = _resolve_conn(o), _opts(o)
    if (c.get("mode") or "").lower() == "jdbc":
        return _ic_jdbc(o, user, password)
    user = c.get("user") or user
    password = c.get("password") or password
    oracledb = _ensure_pkg("oracledb")
    dsn = c.get("dsn") or (f"{c.get('host')}:{c.get('port', 1521)}/"
                           f"{c.get('service') or c.get('database') or o.get('database_name')}")
    cn = oracledb.connect(user=user, password=password, dsn=dsn)   # thin mode
    return _dbapi_to_spark(cn, opts.get("query") or _default_query(o))

"""On-prem / staged connector — reads a table an upstream Copy activity already landed in
OneLake (for on-prem sources Spark can't reach directly)."""


@ingest_connector("onprem", "staged")
def _ic_staged(o, user, password):
    """Read a table an upstream Copy activity already landed in OneLake — for **on-prem** sources
    that Spark can't reach directly. `cp_pl_onprem` copies on-prem->bronze staging via the gateway;
    this connector reads that staged Delta so it flows through the normal bronze pipeline (control
    columns, select, schema naming) into the SAME silver/gold. source_options_json:
    {staging_lakehouse (default 'bronze'), staging_schema (default 'staging'), staging_table}."""
    opts = _opts(o)
    lh = opts.get("staging_lakehouse", "bronze")
    schema = opts.get("staging_schema", "staging")
    table = opts.get("staging_table") or _norm_ident(
        "_".join(x for x in [o.get("source_schema"), o.get("source_table")] if x))
    p = tpath(lh, table, schema)
    if not delta_exists(p):
        raise Exception(f"staged table not found: {lh}.{schema}.{table} "
                        f"(the cp_pl_onprem Copy activity must land it first)")
    return read_path(p)

"""Object-discovery registry. Add a discoverer by dropping a module here and decorating it with
@discoverer("connector_name") — no edits here. A discoverer is fn(datasource_config: dict) ->
list of candidate object dicts (source_schema, source_table, key_columns_json,
source_options_json; any may be None). The metadata step materializes these as source_object
rows with is_active=0."""

DISCOVERERS = {}


def discoverer(*names):
    """Register a discoverer under one or more connector names."""
    def deco(fn):
        for n in names:
            DISCOVERERS[n] = fn
        return fn
    return deco


def register_discoverer(name, fn):
    """Imperative registration (equivalent to @discoverer)."""
    DISCOVERERS[name] = fn


def discover_objects(ds):
    """Return candidate objects for a datasource via its registered discoverer (or None)."""
    fn = DISCOVERERS.get(resolve_connector(ds))
    return fn(ds) if fn else None

"""SQL Server object discovery — enumerate base tables + primary-key columns."""
import json



@discoverer("sqlserver")
def _discover_sqlserver(ds):
    """Enumerate every base table in the source database + its primary-key columns."""
    c = _resolve_conn(ds)
    d = JDBC_DIALECTS["sqlserver"]
    url = c.get("url") or c.get("connection_string") or d["url"].format(
        host=c.get("host") or SOURCE_SERVER, port=c.get("port") or d["port"],
        database=c.get("database") or ds.get("database_name"))
    drv, u, p = _jdbc_driver(c, d), c.get("user"), c.get("password")
    tables = _jdbc_load(url, drv, u, p, query=(
        "SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES "
        "WHERE TABLE_TYPE='BASE TABLE'")).collect()
    # NB: Spark wraps a `query` as a derived table, and SQL Server forbids ORDER BY there —
    # so select ORDINAL_POSITION and sort in Python instead.
    pk = _jdbc_load(url, drv, u, p, query=(
        "SELECT KU.TABLE_SCHEMA t_s, KU.TABLE_NAME t_n, KU.COLUMN_NAME c_n, KU.ORDINAL_POSITION ord "
        "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC "
        "JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KU "
        "ON TC.CONSTRAINT_NAME=KU.CONSTRAINT_NAME AND TC.CONSTRAINT_SCHEMA=KU.CONSTRAINT_SCHEMA "
        "WHERE TC.CONSTRAINT_TYPE='PRIMARY KEY'")).collect()
    keys = {}
    for r in sorted(pk, key=lambda x: x["ord"]):
        keys.setdefault((r["t_s"], r["t_n"]), []).append(r["c_n"])
    return [{"source_schema": t["TABLE_SCHEMA"], "source_table": t["TABLE_NAME"],
             "key_columns_json": json.dumps(keys.get((t["TABLE_SCHEMA"], t["TABLE_NAME"]), [])),
             "source_options_json": None} for t in tables]

"""StatCan WDS object discovery — one object per table_id declared at the datasource."""
import json



@discoverer("statcan_wds")
def _discover_statcan(ds):
    """Materialize one object per table_id declared at the datasource (connection_json.tables),
    seeded with GENERIC http params (the same _ic_http serves it — StatCan is just a zip_csv
    profile). The user then adds filters/select and activates."""
    out = []
    for t in _conn(ds).get("tables", []):
        out.append({"source_schema": None, "source_table": t.get("name") or str(t["table_id"]),
                    "key_columns_json": json.dumps(["REF_DATE", "VECTOR"]),
                    "source_options_json": json.dumps({
                        "url": "https://www150.statcan.gc.ca/t1/wds/rest/"
                               "getFullTableDownloadCSV/{table_id}/{language}",
                        "params": {"table_id": str(t["table_id"]), "language": t.get("language", "en")},
                        "response": {"type": "zip_csv", "url_field": "object", "exclude": "_Meta"}})})
    return out

"""Reusable gold writers (called by the source-query notebooks): SCD1/SCD2/fact merge + the
standard stage-then-gold epilogue."""
from pyspark.sql import functions as F
from delta.tables import DeltaTable



def gold_write(stage, gold_type, gold_table, keys, run_id):
    stage = (stage.withColumn("_gold_run_id", F.lit(run_id))
                  .withColumn("_gold_updated_at", F.current_timestamp()))
    path = tpath("gold", gold_table)
    if gold_type in ("scd1", "fact"):
        merge_upsert(path, stage, keys)
    elif gold_type == "scd2":
        _scd2_merge(stage, path, keys)
    else:
        write_path(stage, path, "overwrite")
    return read_path(path).count()


def _scd2_merge(stage, path, keys):
    stage = row_hash(stage)
    incoming = (stage.withColumn("_effective_start_ts", F.current_timestamp())
                     .withColumn("_effective_end_ts", F.lit(None).cast("timestamp"))
                     .withColumn("_is_current", F.lit(True)))
    if not delta_exists(path):
        write_path(incoming, path, "overwrite")
        return
    tgt = DeltaTable.forPath(spark, path)
    cur = tgt.toDF().where(F.col("_is_current"))
    keycond = [incoming[k] == cur[k] for k in keys]
    changed = (incoming.join(cur, keycond, "inner")
               .where(incoming["_row_hash"] != cur["_row_hash"])
               .select(*[incoming[k].alias(k) for k in keys]))
    if changed.count():
        ec = " AND ".join([f"t.`{k}` = s.`{k}`" for k in keys])
        (tgt.alias("t").merge(changed.alias("s"), ec)
            .whenMatchedUpdate(set={"_is_current": F.lit(False),
                                    "_effective_end_ts": F.current_timestamp()}).execute())
    cur_keys = tgt.toDF().where(F.col("_is_current")).select(*keys)
    to_insert = incoming.join(cur_keys, keys, "left_anti")
    if to_insert.count():
        write_path(to_insert, path, "append")


def build_stage_and_gold(gold_object_id, stage_df, gold_type, stage_table, gold_table, keys, run_id):
    """Standard source-query epilogue: persist the stage table, then merge into gold + log."""
    write_path(stage_df, tpath(STAGE_LH, f"stage_{stage_table}"), "overwrite")
    cnt = gold_write(stage_df, gold_type, gold_table, keys, run_id)
    log_object_run(run_id, gold_object_id, "gold", "SUCCEEDED", target_count=cnt,
                   details={"gold_type": gold_type})
    print(f"gold {gold_table} ({gold_type}): {cnt} rows")
    return cnt

"""Planner entrypoint: read config_db and return the work-list for a pipeline ForEach via
notebookutils.notebook.exit. plan_type: objects (bronze/silver) | models (gold) | steps (main)
| datasets (pbi)."""
import json



def plan(load_group=1, plan_type="objects", **kw):
    lg = int(load_group)
    if plan_type == "objects":
        rows = config_query(
            "SELECT o.object_id,o.source_schema,o.source_table,o.target_name,o.load_type,"
            "o.key_columns_json,o.watermark_column,o.source_options_json,o.suffix,"
            "d.database_name,d.source_name,d.source_type,d.connector,d.connection_json,d.secret_name "
            "FROM dbo.source_object o JOIN dbo.datasource d ON o.source_id=d.source_id "
            "WHERE o.is_active=1 AND o.processing_state='ACTIVE' AND d.load_group=? "
            "ORDER BY o.object_id", (lg,))
    elif plan_type == "models":
        rows = config_query(
            "SELECT model_id,model_name FROM dbo.model WHERE is_active=1 AND load_group=? "
            "ORDER BY model_id", (lg,))
    elif plan_type == "steps":
        rows = config_query(
            "SELECT step_order,step_key,child_pipeline,is_active FROM dbo.steps "
            "WHERE load_group=? ORDER BY step_order", (lg,))
    elif plan_type == "datasets":
        rows = config_query(
            "SELECT dataset_id,workspace_id,dataset_name FROM dbo.pbi_dataset "
            "WHERE is_active=1 AND load_group=?", (lg,))
    else:
        rows = []

    # steps -> keyed object {step_key: is_active} so the main pipeline's If can select by
    # property name (Fabric expressions can't filter()/item() outside a ForEach).
    if plan_type == "steps":
        out = {r["step_key"]: bool(r["is_active"]) for r in rows}
    else:
        for r in rows:
            if "is_active" in r:
                r["is_active"] = bool(r["is_active"])
        out = rows
    print(f"plan {plan_type} lg={lg}: {len(rows)} rows")
    notebookutils.notebook.exit(json.dumps(out, default=str))

"""Bronze entrypoint: load ONE source object via its registered connector and land it in bronze.
All logic lives here so the bronze_worker notebook is a 3-cell shell."""
import json
import traceback

from pyspark.sql import functions as F



def bronze(run_id="manual", object_json="{}", object=None, src_user="", src_password="", **kw):
    """object_json: JSON string of the object config (from the planner); or pass `object` as a dict."""
    o = object if object is not None else json.loads(object_json or "{}")

    def _work():
        oid, load_type = o["object_id"], o["load_type"]
        schema, table = landed_table(o)                        # schema-enabled: (schema, table)
        wm_col = o.get("watermark_column")
        connector = resolve_connector(o)

        df = run_connector(o, src_user, src_password)          # dispatch by connector type
        df = apply_select(df, _opts(o).get("select"))          # config-driven landed schema

        label = ".".join(x for x in [o.get("source_schema"), o.get("source_table")] if x) or table
        df = (df.withColumn("_run_id", F.lit(run_id))
                .withColumn("_source_system", F.lit(o.get("source_name", "")))
                .withColumn("_source_table", F.lit(label))
                .withColumn("_bronze_ingest_ts", F.current_timestamp()))
        cnt = df.count()
        mode = "append" if load_type in ("incremental", "append") else "overwrite"
        write_path(df, tpath("bronze", table, schema), mode=mode)
        if wm_col and wm_col in df.columns and cnt:
            update_watermark(oid, df.agg(F.max(F.col(wm_col))).collect()[0][0])
        log_object_run(run_id, oid, "bronze", "SUCCEEDED", source_count=cnt, target_count=cnt,
                       details={"mode": mode, "connector": connector})
        print(f"bronze {schema}.{table}: {cnt} rows ({mode}, connector={connector})")

    try:
        _work()
    except Exception:
        files_put(f"_cp_err_bronze_{o.get('object_id', 'x')}_{run_id}.txt", traceback.format_exc())
        raise

"""Silver entrypoint: build silver for ONE object — dedupe by key, row-hash, cleanse, DQ +
quarantine, upsert. All logic lives here so the silver_worker notebook is a 3-cell shell."""
import json
import traceback

from pyspark.sql import functions as F, Window



def _dq_condition(rule, colmap):
    col = colmap.get(snake(rule["column_name"])) if rule.get("column_name") else None
    if col is None:
        return F.lit(True)
    t = rule["rule_type"]
    if t == "not_null":
        return col.isNotNull()
    if t == "min":
        return col.isNull() | (col >= float(rule["min_value"]))
    if t == "max":
        return col.isNull() | (col <= float(rule["max_value"]))
    if t == "allowed_values":
        return col.isNull() | col.isin(json.loads(rule["allowed_values_json"]))
    if t == "expression":
        return F.expr(rule["rule_expression"])
    return F.lit(True)


def silver(run_id="manual", object_json="{}", object=None, **kw):
    """object_json: JSON string of the object config (from the planner); or pass `object` as a dict."""
    o = object if object is not None else json.loads(object_json or "{}")

    def _work():
        oid = o["object_id"]
        schema, table = landed_table(o)                        # schema-enabled: (schema, table)
        keys = [snake(k) for k in json.loads(o["key_columns_json"])]
        bp = tpath("bronze", table, schema)
        if not delta_exists(bp):
            print(f"skip {schema}.{table}: no bronze")
            return
        df = read_path(bp)
        ingest_ts = df["_bronze_ingest_ts"] if "_bronze_ingest_ts" in df.columns else F.current_timestamp()
        biz = [c for c in df.columns if not c.startswith("_")]
        sdf = df.select([F.col(c).alias(snake(c)) for c in biz] + [ingest_ts.alias("_bronze_ingest_ts")])
        if "rowguid" in sdf.columns:
            sdf = sdf.drop("rowguid")
        if all(k in sdf.columns for k in keys):
            w = Window.partitionBy(*keys).orderBy(F.col("_bronze_ingest_ts").desc())
            sdf = sdf.withColumn("_rn", F.row_number().over(w)).where(F.col("_rn") == 1).drop("_rn")
        sdf = sdf.drop("_bronze_ingest_ts")

        # cleanse (fix rows) BEFORE DQ validation (quarantine)
        crules = config_query(
            "SELECT * FROM dbo.cleanse_rule WHERE object_id=? AND is_active=1 ORDER BY apply_order", (oid,))
        sdf = apply_cleansing(sdf, crules)

        colmap = {c: F.col(c) for c in sdf.columns}
        rules = config_query("SELECT * FROM dbo.dq_rule WHERE object_id=? AND is_active=1", (oid,))
        pass_all = F.lit(True)
        for rule in rules:
            cond = _dq_condition(rule, colmap)
            failed = sdf.where(~cond).count() if rule.get("column_name") else 0
            append_rows("dq_result", [{"run_id": run_id, "object_id": oid, "rule_id": rule["rule_id"],
                                       "failed_count": failed, "passed_count": sdf.count() - failed,
                                       "status": "FAIL" if failed else "PASS", "evaluated_at": now_ts()}])
            if str(rule["severity"]).lower() == "error":
                pass_all = pass_all & cond

        good, bad = sdf.where(pass_all), sdf.where(~pass_all)
        q_cnt = bad.count()
        if q_cnt:
            write_path(bad.withColumn("_run_id", F.lit(run_id)).withColumn("_quarantined_at", F.current_timestamp()),
                       tpath(QUAR_LH, f"quarantine_{table}", schema), mode="overwrite")
        good = row_hash(good).withColumn("_silver_run_id", F.lit(run_id)) \
                             .withColumn("_silver_updated_at", F.current_timestamp())
        sp = tpath("silver", table, schema)
        if all(k in good.columns for k in keys):
            # dedup on the key set before merge so a merge never sees duplicate source keys — this
            # is also how keyless sources dedup on the full row (key_columns_json = ["_row_hash"]).
            merge_upsert(sp, good.dropDuplicates(keys), keys)
        else:
            write_path(good, sp, mode="overwrite")
        s_cnt = read_path(sp).count()
        log_object_run(run_id, oid, "silver", "SUCCEEDED", source_count=sdf.count(),
                       target_count=s_cnt, quarantine_count=q_cnt)
        print(f"silver {schema}.{table}: {s_cnt} rows, quarantined {q_cnt}")

    try:
        _work()
    except Exception:
        files_put(f"_cp_err_silver_{o.get('object_id', 'x')}_{run_id}.txt", traceback.format_exc())
        raise

"""Metadata entrypoint: (1) discover objects at each datasource and register them into
source_object as is_active=0; (2) snapshot columns + log schema drift for the ACTIVE objects
(SQL Server). All logic lives here so the metadata_worker notebook is a 3-cell shell."""
import traceback

from pyspark.sql import functions as F


_INSERT = ("INSERT INTO dbo.source_object (object_id,source_id,source_schema,source_table,"
           "target_name,load_type,key_columns_json,watermark_column,watermark_type,is_active,"
           "processing_state,source_options_json,suffix) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)")


def _register_discovered(run_id, lg):
    for ds in config_query("SELECT * FROM dbo.datasource WHERE load_group=? AND is_active=1", (lg,)):
        conn = resolve_connector(ds)
        try:
            cands = discover_objects(ds)
        except Exception:
            files_put(f"_cp_err_discover_{ds['source_name']}_{run_id}.txt", traceback.format_exc())
            print(f"discover {ds['source_name']} FAILED (see Files) — continuing")
            continue
        if cands is None:
            print(f"discover {ds['source_name']}: no discoverer for '{conn}', skip")
            continue
        sid = ds["source_id"]
        existing = {(r["source_schema"] or "", r["source_table"]) for r in config_query(
            "SELECT source_schema, source_table FROM dbo.source_object WHERE source_id=?", (sid,))}
        inserts = []
        for cand in cands:
            sch, tbl = cand.get("source_schema"), cand.get("source_table")
            if (sch or "", tbl) in existing:               # already represented — preserve tweaks
                continue
            oid = _norm_ident(f"{ds['source_name']}_{sch or 'dbo'}_{tbl}")
            inserts.append((oid, sid, sch, tbl, None, "full", cand.get("key_columns_json"),
                            None, None, 0, "ACTIVE", cand.get("source_options_json"), None))
        config_exec_many(_INSERT, inserts)
        log_object_run(run_id, ds["source_name"], "discover", "SUCCEEDED", target_count=len(inserts))
        print(f"discover {ds['source_name']}: +{len(inserts)} new object(s) is_active=0 "
              f"({len(cands)} found, {len(existing)} already registered)")


def _snapshot_columns(run_id, lg, src_user, src_password):
    objs = config_query(
        "SELECT o.object_id,o.source_schema,o.source_table,d.database_name,d.connector,"
        "d.source_type,d.secret_name,d.connection_json "
        "FROM dbo.source_object o JOIN dbo.datasource d ON o.source_id=d.source_id "
        "WHERE o.is_active=1 AND o.processing_state='ACTIVE' AND d.load_group=? ORDER BY o.object_id",
        (lg,))
    p = tpath("config", "source_column")
    d = JDBC_DIALECTS["sqlserver"]
    for o in objs:
        oid, schema, table = o["object_id"], o["source_schema"], o["source_table"]
        if resolve_connector(o) != "sqlserver":
            log_object_run(run_id, oid, "metadata", "SKIPPED", details={"connector": resolve_connector(o)})
            print(f"metadata {oid}: skip column snapshot (connector {resolve_connector(o)})")
            continue
        c = _resolve_conn(o)
        url = c.get("url") or c.get("connection_string") or d["url"].format(
            host=c.get("host") or SOURCE_SERVER, port=c.get("port") or d["port"],
            database=c.get("database") or o.get("database_name"))
        rows = _jdbc_load(url, _jdbc_driver(c, d), c.get("user") or src_user,
                          c.get("password") or src_password, query=(
            "SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS "
            f"WHERE TABLE_SCHEMA='{schema}' AND TABLE_NAME='{table}'")).collect()
        cur = {r["COLUMN_NAME"]: r["DATA_TYPE"] for r in rows}
        prev = set()
        if delta_exists(p):
            prev = {r["column_name"] for r in read_path(p).where(F.col("object_id") == oid).collect()}
        curset = set(cur)
        if prev:
            ev = [{"event_id": f"{run_id}_{oid}_{col}", "run_id": run_id, "object_id": oid,
                   "column_name": col, "drift_type": dt, "severity": sv, "details": "{}",
                   "detected_at": now_ts()}
                  for col, dt, sv in ([(x, "COLUMN_ADDED", "info") for x in sorted(curset - prev)] +
                                      [(x, "COLUMN_REMOVED", "warning") for x in sorted(prev - curset)])]
            if ev:
                append_rows("schema_drift_event", ev)
        snap = [{"object_id": oid, "column_name": col, "source_data_type": t,
                 "discovered_at": now_ts(), "is_active": True} for col, t in cur.items()]
        merge_upsert(p, spark.createDataFrame(snap), ["object_id", "column_name"])
        log_object_run(run_id, oid, "metadata", "SUCCEEDED", target_count=len(cur))
        print(f"metadata {oid}: {len(cur)} cols")


def metadata(run_id="manual", load_group=1, src_user="", src_password="", **kw):
    lg = int(load_group)
    try:
        seed_control_tables()       # pre-create audit tables so parallel workers don't race to create
        start_run(run_id, {"engine": "pipeline", "load_group": lg})
        _register_discovered(run_id, lg)     # 1) auto-register objects (is_active=0)
        _snapshot_columns(run_id, lg, src_user, src_password)   # 2) column drift for active objects
    except Exception:
        files_put(f"_cp_err_metadata_{run_id}.txt", traceback.format_exc())
        raise

"""Gold entrypoint: build ONE model's gold objects in dependency (topo) order by running each
object's source-query notebook. All logic lives here so the gold_runner notebook is a shell."""
import traceback



def gold(run_id="manual", model_id=1, **kw):
    mid = int(model_id)

    def _work():
        gobjs = config_query(
            "SELECT gold_object_id, source_query_notebook FROM dbo.gold_object "
            "WHERE model_id=? AND is_active=1", (mid,))
        ids = [g["gold_object_id"] for g in gobjs]
        nb_by_id = {g["gold_object_id"]: g["source_query_notebook"] for g in gobjs}
        deps = config_query(
            "SELECT parent_gold_object_id, child_gold_object_id FROM dbo.gold_dependency", ())
        edges = [(d["parent_gold_object_id"], d["child_gold_object_id"]) for d in deps
                 if d["parent_gold_object_id"] in ids and d["child_gold_object_id"] in ids]
        levels = topo_levels(ids, edges)
        print(f"model {mid} gold DAG levels:", levels)
        order = []
        for level in levels:
            for gid in level:
                print(f">>> {gid} -> {nb_by_id[gid]}")
                notebookutils.notebook.run(nb_by_id[gid], 1800, {"run_id": run_id})
                order.append(gid)
        print("gold build order:", order)

    try:
        _work()
    except Exception:
        files_put(f"_cp_err_gold_model{mid}_{run_id}.txt", traceback.format_exc())
        raise

"""Dropbox intake entrypoint — process ONE dropped file (event-triggered, one run per file).

Landing lakehouse LH_Filedrop/Files:
    newfile/<schema>/<file>   -> medallion schema = <schema>
    newfile/<file>            -> medallion schema = dbo
Each csv/txt file -> one table; each xlsx/xls sheet -> its own table (<file>_<tab>).
Bronze APPENDS every drop; silver dedups on the full row hash. Idempotent via the
dropbox_ledger (skip re-drops of identical content) AND the silver row-hash dedup (so even a
duplicate event can't create duplicate rows). Processed files are moved to archive/Y/M/D/<ts>/.
"""
import json
import os
import tempfile
import traceback

from pyspark.sql import functions as F


FILEDROP_LAKEHOUSE = "LH_Filedrop"


def _filedrop_guid():
    for lh in notebookutils.lakehouse.list():
        if lh["displayName"] == FILEDROP_LAKEHOUSE:
            return lh["id"]
    raise Exception(f"lakehouse {FILEDROP_LAKEHOUSE} not found")


def _download(abfss, base, tries=3):
    """Copy the OneLake file locally; retry (Excel/clients can fire the event mid-write)."""
    import time
    last = None
    for _ in range(tries):
        try:
            local = os.path.join(tempfile.gettempdir(), f"cp_dropin_{base}_{abs(hash(abfss)) % 10**8}")
            notebookutils.fs.cp(abfss, "file:" + local, True)
            return local
        except Exception as e:
            last = e
            time.sleep(3)
    raise last


def _hash_file(local):
    import hashlib
    h = hashlib.sha256()
    with open(local, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _rm(local):
    try:
        os.remove(local)
    except OSError:
        pass


def _already_processed(file_key, fhash):
    p = tpath("config", "dropbox_ledger")
    if not delta_exists(p):
        return False
    return read_path(p).where((F.col("file_key") == file_key) &
                              (F.col("content_hash") == fhash)).limit(1).count() > 0


def _ensure_datasource(schema):
    """Idempotently register the schema as a `file` datasource; return its source_id."""
    config_exec(
        "IF NOT EXISTS (SELECT 1 FROM dbo.datasource WHERE source_name=?) "
        "INSERT INTO dbo.datasource (source_name, source_type, load_group, ingestion_mode, "
        "is_active, connector) VALUES (?, 'FILE', 0, 'file', 1, 'file')", (schema, schema))
    return config_query("SELECT MIN(source_id) AS sid FROM dbo.datasource WHERE source_name=?",
                        (schema,))[0]["sid"]


def _register_object(oid, sid, tbl, keys_json, opts_json):
    config_exec("DELETE FROM dbo.source_object WHERE object_id=?", (oid,))
    config_exec(
        "INSERT INTO dbo.source_object (object_id, source_id, source_table, target_name, load_type,"
        " key_columns_json, is_active, processing_state, source_options_json) "
        "VALUES (?,?,?,?,?,?,?,?,?)",
        (oid, sid, tbl, f"dropbox_{tbl}", "append", keys_json, 1, "ACTIVE", opts_json))


def _write_ledger(file_key, fhash, schema, n):
    append_rows("dropbox_ledger", [{"file_key": file_key, "content_hash": fhash,
                                    "schema_name": schema, "object_count": n,
                                    "status": "PROCESSED", "processed_at": now_ts()}])


def _archive(guid, rel):
    # Archive by DATE (not per-run timestamp) so a batch dropped together lands in ONE day folder,
    # even though each file is processed by its own event-triggered run. Concurrent runs just mv
    # into the same folder (distinct filenames). Same-name re-drops in a day get a time suffix.
    ts = now_ts()
    fname = rel.rsplit("/", 1)[-1]
    root = f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{guid}/Files"
    folder = f"{root}/archive/{ts:%Y/%m/%d}"
    src = f"{root}/{rel}"
    try:
        notebookutils.fs.mv(src, f"{folder}/{fname}", True)
        print(f"dropbox: archived -> archive/{ts:%Y/%m/%d}/{fname}")
    except Exception:                                        # name already there (re-drop) — keep both
        stem, dot, ext = fname.rpartition(".")
        alt = f"{(stem or fname)}_{ts:%H%M%S}{('.' + ext) if dot else ''}"
        try:
            notebookutils.fs.mv(src, f"{folder}/{alt}", True)
            print(f"dropbox: archived -> archive/{ts:%Y/%m/%d}/{alt}")
        except Exception as e:
            print("dropbox: archive mv warning:", str(e)[:150])


def _run(file_path, run_id):
    seed_control_tables()
    guid = _filedrop_guid()
    # the OneLake event Subject is URL-encoded (spaces -> %20) and prefixed (/Files/newfile/..);
    # decode, then normalize to start at 'newfile' regardless of any prefix.
    import urllib.parse
    file_path = urllib.parse.unquote(file_path or "")
    parts = file_path.strip("/").replace("\\", "/").split("/")
    if "newfile" in parts:
        parts = parts[parts.index("newfile"):]
    if not parts or parts[0] != "newfile" or len(parts) < 2:
        print(f"dropbox: '{file_path}' is not a file under newfile/ — ignored")
        return "ignored (not under newfile/)"
    rel = "/".join(parts)
    fname = parts[-1]
    schema = _norm_ident(parts[1]) if len(parts) >= 3 else "dbo"
    ext = fname.rsplit(".", 1)[-1].lower() if "." in fname else ""
    base = _norm_ident(fname.rsplit(".", 1)[0])
    abfss = f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{guid}/Files/{rel}"

    local = _download(abfss, base)
    fhash = _hash_file(local)
    file_key = f"{schema}/{fname}"
    if _already_processed(file_key, fhash):
        print(f"dropbox: {file_key} ({fhash[:8]}) already processed — skip + archive duplicate")
        _rm(local)
        _archive(guid, rel)                              # keep newfile/ clean
        return "skipped (already processed)"

    if ext in ("xlsx", "xls"):                               # one object per sheet
        import pandas as pd
        engine = "openpyxl" if ext == "xlsx" else "xlrd"
        _ensure_pkg(engine)
        sheets = pd.ExcelFile(local, engine=engine).sheet_names
        objs = [(f"{base}_{_norm_ident(s)}", {"file_abfss": abfss, "format": ext, "sheet": s})
                for s in sheets]
    else:                                                    # csv / txt -> one object
        objs = [(base, {"file_abfss": abfss, "format": "txt" if ext == "txt" else "csv"})]
    _rm(local)

    sid = _ensure_datasource(schema)
    loaded = 0
    for tbl, opts in objs:
        opts["landed"] = {"table": tbl}                      # clean <schema>.<tbl>, no dbo_ prefix
        oid = _norm_ident(f"dropbox_{schema}_{tbl}")
        keys_json, opts_json = json.dumps(["_row_hash"]), json.dumps(opts)
        _register_object(oid, sid, tbl, keys_json, opts_json)
        o = {"object_id": oid, "source_id": sid, "source_name": schema, "source_schema": None,
             "source_table": tbl, "connector": "file", "secret_name": None, "load_type": "append",
             "key_columns_json": keys_json, "source_options_json": opts_json}
        oj = json.dumps(o)
        bronze(run_id=run_id, object_json=oj)
        silver(run_id=run_id, object_json=oj)
        loaded += 1
        print(f"dropbox: loaded {schema}.{tbl}")

    _write_ledger(file_key, fhash, schema, loaded)
    _archive(guid, rel)
    print(f"dropbox: DONE {file_key} -> {loaded} table(s) in schema '{schema}'")
    return f"processed ({loaded} table{'s' if loaded != 1 else ''})"


def _list_newfile(guid):
    root = f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{guid}/Files/newfile"
    out = []

    def walk(path):
        try:
            entries = notebookutils.fs.ls(path)
        except Exception:
            return
        for e in entries:
            (walk(e.path) if e.isDir else out.append(e.path))
    walk(root)
    return out


def _scan(run_id):
    """Process every file currently sitting under newfile/ (manual/scheduled batch, or a
    catch-up sweep). Per-file isolation: one bad file is reported, the rest still process."""
    guid = _filedrop_guid()
    files = _list_newfile(guid)
    print(f"dropbox scan: {len(files)} file(s) under newfile/")
    results = []
    for abfss in files:
        rel = abfss.split("/Files/", 1)[-1]
        try:
            results.append((rel, _run(rel, run_id) or "processed"))
        except Exception as e:
            files_put(f"_cp_err_dropbox_{_norm_ident(rel)}_{run_id}.txt", traceback.format_exc())
            results.append((rel, f"FAILED: {str(e)[:120]}"))
    ok = sum(1 for _, s in results if not s.startswith("FAILED"))
    print(f"dropbox scan DONE: {ok}/{len(results)} ok")
    for rel, s in results:
        print(f"  [{'OK ' if not s.startswith('FAILED') else 'ERR'}] {rel:<40} {s}")
    return results


def dropbox(file_path="", run_id="manual", **kw):
    """Process one dropped file (path relative to LH_Filedrop/Files, e.g. 'newfile/voc/x.xlsx').
    With no file_path, SCAN and process everything currently under newfile/."""
    try:
        return _run(file_path, run_id) if (file_path or "").strip() else _scan(run_id)
    except Exception:
        files_put(f"_cp_err_dropbox_{_norm_ident(file_path) or 'scan'}_{run_id}.txt", traceback.format_exc())
        raise

# --- worker namespace (so the thin notebooks call workers.<layer>(...) identically
#     whether this is the %run bundle or, later, `from cp import workers`) ---
import types as _types
workers = _types.SimpleNamespace(plan=plan, bronze=bronze, silver=silver,
                                 metadata=metadata, gold=gold, dropbox=dropbox)

print("cp_framework loaded")

